### ISSUE TITLE
Java 9 Meetup için ön hazırlığın yapılması

### ISSUE THREAD

**Issue by tanerdiler** [JUGIstanbul/meetings#2]
Açılışta, meetup serisinin amacı ve gelecek meetupların paylaşımı yapıldıktan sonra

- Java 9 ile gelen, öne çıkan yenilikler
- Collection factory methods (örnek gösterilebilir)
- Stream API (örnek gösterilebilir)
- JShell (örnek gösterilebilir)
      * JShell sunumunda bir örnek var o uygulanabilir. 
      * Örnek bol refactor etmeli olmalı ki kapasitesini gösterebilelim.
- HTTP/2 (incubator modüldü, kalıcı hale geldi mi bakmalı)
   - JAva 11'de incubator'lukten çıkmış. http://zetcode.com/java/httpclient/
- Module API + JLink --> Taner --> Bir senaryo üzerinden gideceğim

**Comment by hakdogan** [comment]
Açılışta, meetup serisinin amacı ve gelecek meetupların paylaşımı yapıldıktan sonra

- Java 9 ile gelen, öne çıkan yenilikler
- Collection factory methods (örnek gösterilebilir)
- Stream API (örnek gösterilebilir)
- JShell (örnek gösterilebilir)
- JLink
- HTTP/2 (incubator modüldü, kalıcı hale geldi mi bakmalı)
- Module API (örneklendirilecek)

biçiminde ilerleyebiliriz. 

Ne dersiniz?

**Comment by tanerdiler** [comment]
Benim daha önce Haliç Üniversitesinde yaptığım bir sunum vardı onu bulmaya çalışayım.

**Comment by tanerdiler** [comment]
Buldum şimdi sadece JShell ve Http2 Client üzerine sunum yapmışım. sunum linkleri https://github.com/JUGIstanbul/meetings/issues/7 içerisinde.

**Comment by tanerdiler** [comment]
JLink  ve Module Api bende. Burası zaten zaman alacak...

**Comment by hakdogan** [comment]
> JLink ve Module Api bende. Burası zaten zaman alacak...

Elbette, 40-45 dakikalık bir oturum için o 2 konuyu cover etmek zor bile. Diğer konulardan sözlü olarak bahsedip geçeceğiz.

**Comment by tanerdiler** [comment]
https://docs.google.com/presentation/d/18hGFjik3ro8tKDDUkwBqXpuVe3BW3tLNTNvHUZtJkAU/edit?usp=sharing

Etkinlik sunumunu burada hazırlayalım...

**Comment by tanerdiler** [comment]
Java 9 ile ilgili hazırladığım kodlar var https://github.com/tanerdiler/java9

**Comment by tanerdiler** [comment]
bahsettimğimiz her konu için issue açtım. bunu kapatıyorum.
