### ISSUE TITLE
CrowdCast test sürüşü

### ISSUE THREAD

**Issue by hakdogan** [JUGIstanbul/meetings#5]
Bu toolu daha önce hiç kullanmadım, sanırım siz de hiç kullanmadınız. Etkinlik günü sürprizlerle karşılaşmamak adına bir test sürüşü yapabilir miyiz?

**Comment by altuga** [comment]
Bana uygun

**Comment by hakdogan** [comment]
When? @tanerdiler

**Comment by hakdogan** [comment]
Başarıyla gerçekleştirildi
