### ISSUE TITLE
Java 9 Sunumuna JakartaEE sponsorluk görselinin eklenmesi

### ISSUE THREAD

**Issue by tanerdiler** [JUGIstanbul/meetings#6]
Crowdcast.io üzerinden yaptığımız sunumlarda JakartaEE https://drive.google.com/file/d/1kcwHsaoZYd6WFgLgQ3ZErasTuYYCqUJP/view görselinin de gösterilmesini istiyor. Sunuma koymayı unutmayalım.

**Comment by altuga** [comment]
İşi kime @hakdogan  mı atandı ?

**Comment by tanerdiler** [comment]
Ekledim
